FROM docker.io/library/debian
RUN apt-get update -y && apt-get install -y --no-install-recommends make tidy python3 python3-pip
RUN apt-get update -y && apt-get install -y --no-install-recommends markdown

WORKDIR /home