#!/bin/bash

function sections() {
    find sections -maxdepth 1 -mindepth 1 -type d |
        sed  -r -s 's#^sections/([^/]*)$#\1#' |
        sort |
        tr "\n" " "
}

function articles() {
    section="$1"
    find "sections/$section" -iname '*.md' |
        sed -r -e 's/(.*).md$/\1.article.auto.html/' |
        sort |
        tr '\n' ' '
}

{
    for section in $(sections)
    do
        echo sections.auto.html: sections/${section}.section.auto.html
        echo                     sections/${section}.section.auto.html: $(articles $section)
    done
} > sections.auto.mk

make all --silent
